# Generated by Django 3.1.7 on 2021-04-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='userId',
            field=models.CharField(max_length=30),
        ),
    ]
