# Generated by Django 3.1.7 on 2021-04-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_remove_webhook_contact_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='errorCode',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='localDeviceId',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='name',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='states',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='tfa',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='userId',
        ),
        migrations.AddField(
            model_name='webhook',
            name='data',
            field=models.JSONField(default=False, max_length=100),
        ),
    ]
